theme: jekyll-theme-cayman
remote_theme: just-the-docs/just-the-docs

title: "Autonomous Sailboat"
logo: "/assets/logo.png"

color_scheme: foo

footer_content: "EPFL©2022 CS-358 | Project made by Felix Rodriguez, Ghita Tagemouati, Iris Segard, Marc Pitteloud, Ugo Balducci"